import Head from 'next/head';
import { ISbStoryData, ISbStoryParams, StoryblokComponent, getStoryblokApi, useStoryblokState } from '@storyblok/react';
import { Box, useThemeUI } from 'theme-ui';
import { useEffect } from 'react';
interface StoryProps {
  story: ISbStoryData | null;
}
export default function Home({ story }: StoryProps) {
  story = useStoryblokState(story, { customParent: 'http://localhost:3000/' });

  return (
    <>
      <Head>
        <title>Storyblok - NextJS - Theme UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" sx={{ bg: 'background' }}>
        <StoryblokComponent blok={story?.content} />
      </Box>
    </>
  );
}

export async function getStaticProps() {
  let slug = 'home';

  let sbParams: ISbStoryParams = {
    version: 'draft', // or 'published'
  };

  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams);

  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
    revalidate: 3600,
  };
}
